stages:
  - prepare
  - deploy

prepare:
  stage: prepare
  image: alpine:latest  # Use Alpine to create the ZIP
  script:
    - apk update && apk add zip
    - zip -r app.zip app.py requirements.txt
  artifacts:
    paths:
      - app.zip

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    - echo "$AZURE_PUBLISH_PROFILE" > publishprofile.xml
    - az webapp deployment source config-zip --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_WEBAPP_NAME" --src app.zip
